const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                display: ['Geist', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
            },
            colors: {
                surface: '#f8f9ff',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#464554',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                outline: '#767586',
                'outline-variant': '#c7c4d7',
                'surface-tint': '#494bd6',
                primary: '#4648d4',
                'on-primary': '#ffffff',
                'primary-container': '#6063ee',
                'on-primary-container': '#fffbff',
                'inverse-primary': '#c0c1ff',
                secondary: '#565e74',
                'on-secondary': '#ffffff',
                'secondary-container': '#dae2fd',
                'on-secondary-container': '#5c647a',
                tertiary: '#904900',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#b55d00',
                'on-tertiary-container': '#fffbff',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'primary-fixed': '#e1e0ff',
                'primary-fixed-dim': '#c0c1ff',
                'on-primary-fixed': '#07006c',
                'on-primary-fixed-variant': '#2f2ebe',
                'secondary-fixed': '#dae2fd',
                'secondary-fixed-dim': '#bec6e0',
                'on-secondary-fixed': '#131b2e',
                'on-secondary-fixed-variant': '#3f465c',
                'tertiary-fixed': '#ffdcc5',
                'tertiary-fixed-dim': '#ffb783',
                'on-tertiary-fixed': '#301400',
                'on-tertiary-fixed-variant': '#703700',
                background: '#f8f9ff',
                'on-background': '#0b1c30',
                'surface-variant': '#d3e4fe',
            },
            boxShadow: {
                'card': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)',
                'ambient': '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)',
            }
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
